version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx docs/"
      - "python ./docs/pre_build.py"

python:
  install:
    - requirements: docs/requirements.txt


sphinx:
  configuration: docs/conf.py