version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx ngff_spec/"
      - "python ./ngff_spec/pre_build.py"

python:
  install:
    - requirements: requirements.txt


sphinx:
  configuration: ngff_spec/conf.py
  builder: html
  fail_on_warning: true