[project]
name = "ngff-spec"
dynamic = ["version"]
description = "Next-generation file format specification"
requires-python = ">=3.10"

dependencies = [
    "json-schema-for-humans",
    "json_with_comments",
    "jupyter-book==2.0.0b3",
    "jsonschema_markdown",
    "mystmd==1.6.3",
    "tomli",
]

[project.optional-dependencies]
testing = [
    "codespell",
    "pytest",  # https://docs.pytest.org/en/latest/contents.html
]

[dependency-groups]
test = ["pytest"]
lint = ["codespell", "prek"]
dev = [
  "rust-just",
  { include-group = "test" },
  { include-group = "lint" }
]

[tool.codespell]
ignore-regex = '\bComparin\b'
skip = ".git,.codespellrc,references.bib,.venv,.tox,*.css,_build"
ignore-words-list = "commend,Fuchsia"

[tool.hatch.version]
path = "_version.py"

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling>=1.8.0,<1.21.1"]
build-backend = "hatchling.build"
