name: Issue
description: Report an ngff-spec technical issue
title: "[Issue]: "
body:
  - type: markdown
    attributes:
      value: |
        Note: spec-level considerations should usually go to https://github.com/ome/ngff/issues.
        Please use this repo for typos, docs structure, or website/build issues.
  - type: textarea
    id: details
    attributes:
      label: Describe the issue
      placeholder: Write your issue here...
    validations:
      required: true
